# Training Configuration for Wall-X Robotic Multi-Modal Learning
# This configuration supports multi-modal learning with vision, language, and action data

# Model and paths configuration
log_name: "robotic_training"
log_project: "vla_training"
model_type: wall-oss
pretrained_wallx_path: "/x2robot_v2/geoffrey/wall-x/wall-oss-flow"  # Must set
save_path: "/x2robot_v2/geoffrey/wall-x/workspace/checkpoints"                # Must set
use_fast_tokenizer: False                       # True: train FAST, False: train Flow
action_tokenizer_path: None         # Must set if use_fast_tokenizer is true

# Torch Profile
profile: False
profile_save_path: /x2robot_v2/geoffrey/wall-x/workspace/
profile_wait_iters: 10
profile_warmup_iters: 5
profile_active_iters: 2

# Training hyperparameters
num_warmup_steps: 100
num_training_steps: 64000000
learning_rate: 0.00009
min_lr: 0.00005
num_epoch: 100
gradient_accumulation_steps: 32
batch_size_per_gpu: 8
padding_side: left
epoch_save_interval: 10

# Training optimization settings
FSDP2: True
torch_compile: False

# Robot configuration - Define degrees of freedom for each component
dof_config:
  shoulder_pan.pos: 1
  shoulder_lift.pos: 1
  elbow_flex.pos: 1
  wrist_flex.pos: 1
  wrist_roll.pos: 1
  gripper.pos: 1

# Agent proprioception configuration (typically matches DOF config)
agent_pos_config:
  shoulder_pan.pos: 1
  shoulder_lift.pos: 1
  elbow_flex.pos: 1
  wrist_flex.pos: 1
  wrist_roll.pos: 1
  gripper.pos: 1

# # Checkpoint resuming configuration
# resume:
#   ckpt: "/path/to/resume_model/"
#   load_ckpt_only: true

# Data configuration
data:
  use_lerobot: true

  # LeRobot dataset configuration
  lerobot_config:
    repo_id: "20250926/pickandplace"
    root: null
    episodes: null
    image_transforms: null
    delta_timestamps: null
    tolerance_s: 1e-4
    revision: null
    force_cache_sync: false
    download_videos: true
    video_backend: null

  action_horizon: 32
  train_test_split: 0.95

  # Action keys for observation and prediction
  obs_action_keys:
    - shoulder_pan.pos
    - shoulder_lift.pos
    - elbow_flex.pos
    - wrist_flex.pos
    - wrist_roll.pos
    - gripper.pos

  predict_action_keys:
    - shoulder_pan.pos
    - shoulder_lift.pos
    - elbow_flex.pos
    - wrist_flex.pos
    - wrist_roll.pos
    - gripper.pos

  # Image resolution configuration for different camera views
  resolution:
    face_view: 256
    left_wrist_view: 256
    right_wrist_view: 256
    move1_view: 256
    move2_view: 256
    top_view: 256
    wall_view: 256
    multi_modal: 256
